### PR TITLE
CHORE: Issue & Pull Request Template

### PR DESCRIPTION
**Pull request by iShelar**
Issue #5

### CODE REVIEW

**Comment by iShelar** [comment]
Hi @supminn, I was trying to push the changes to previous branch but every commit is reflecting here.

**Comment by supminn** [comment]
> Hi @supminn, I was trying to push the changes to previous branch but every commit is reflecting here.

- Hi @iShelar, can you create a new branch referenced from `main` and added the changes for #5? In this way, you would be raising the PR against the `main` branch and not `develop`.

**Comment by iShelar** [comment]
> > Hi @supminn, I was trying to push the changes to previous branch but every commit is reflecting here.
> 
> * Hi @iShelar, can you create a new branch referenced from `main` and added the changes for [Add a template for Issue and Pull Request #5](https://github.com/supminn/expense_tracker/issues/5)? In this way, you would be raising the PR against the `main` branch and not `develop`.

Hi @supminn, I think develop is not merged yet to the main branch. We'll require latest updated branch.

**Comment by supminn** [comment]
Hi @iShelar 
- Please create a new branch referenced from `main` and added the changes for #5.
- Make sure you raise the PR against `main` branch.
Closing this PR.

**Pull request closed without merging**
